#!/usr/bin/env bash

set -e
echo "Updating nix"
updnix=$(sudo nixos-rebuild switch --flake ~/dots/.config/Nixos/#eukaryotic)

if [ -n "$updnix" ]; then
	pushd "$HOME/dots/.config/Nixos" || exit
	git add .
	if [ "$EDITOR" = "nvim" ]; then
		git diff -U0 '*.nix'
	fi
	git commit
	git push -u origin main
fi

echo "All done!"
popd
