;; -*- lexical-binding: t; -*-
(add-to-list 'custom-theme-load-path "~/.emacs.d/themes/")
(add-to-list 'load-path "~/.emacs.d/lisp/")
(load-theme 'saturn t)
(setenv "MANWIDTH" "200")
;; (setq shell-file-name "bash")
;; (setq shell-command-switch "-ic")
(setq inhibit-startup-screen t)
(setq initial-scratch-message nil)
(setq inhibit-startup-echo-area-message t)
(setq initial-scratch-message nil)
(setq initial-buffer-choice nil)
(setq inhibit-x-resources t)
(setq inhibit-startup-buffer-menu t)
(setq-default bidi-display-reordering 'left-to-right)
(setq-default bidi-paragraph-direction 'left-to-right)
(setq bidi-inhibit-bpa t)
(advice-add #'display-startup-screen :override #'ignore)
(scroll-bar-mode -1)
(tool-bar-mode -1)
(save-place-mode 1)
(menu-bar-mode -1)
(global-font-lock-mode t)
(global-auto-revert-mode t)
(set-fringe-mode 8)
(size-indication-mode 1)
;;(global-hl-line-mode 1)
;;(setq display-line-numbers-type 'relative)
;;(add-hook 'prog-mode-hook #'display-line-numbers-mode)
(setq visible-bell nil)
(setq ring-bell-function nil)
(push '(font . "Iosevka")default-frame-alist)
(global-visual-line-mode t)
(advice-add #'x-apply-session-resources :override #'ignore)
(defvar default-file-name-handler-alist file-name-handler-alist)
(unless (daemonp)
  (advice-add #'display-startup-echo-area-message :override #'ignore))
(setq frame-inhibit-implied-resize t)
(setq package-enable-at-startup nil)

(provide 'early-init)
