(add-to-list 'custom-theme-load-path "~/.emacs.d/themes/")
(load-theme 'morest t)
(setq package-enable-at-startup nil)
(setq inhibit-startup-screen t)
(setq initial-scratch-message nil)
(setq inhibit-startup-echo-area-message t)
(setq initial-scratch-message nil)
(setq initial-buffer-choice nil)
(setq fill-column 80)
(scroll-bar-mode -1)
(tool-bar-mode -1)
(save-place-mode 1)
(menu-bar-mode -1)
(global-font-lock-mode t)
(global-auto-revert-mode t)
(set-fringe-mode 8)
(size-indication-mode 1)
;;(global-hl-line-mode 1)
;;(add-hook 'prog-mode-hook #'display-line-numbers-mode)
(setq visible-bell t)
(push '(font . "iosevka custom" )default-frame-alist)
(global-visual-line-mode t)
(advice-add #'x-apply-session-resources :override #'ignore)
(defvar default-file-name-handler-alist file-name-handler-alist)
(unless (daemonp)
  (advice-add #'display-startup-echo-area-message :override #'ignore))
(setq frame-inhibit-implied-resize t)
(provide 'early-init)
