;;-*- lexical-binding: t; -*-
(setq package-enable-at-startup nil)
(set-frame-font "Fira Code 14 nil t")
(add-to-list 'custom-theme-load-path "~/.emacs.d/themes/")
(load-theme 'morest t)
(setq inhibit-startup-screen t)
(setq initial-scratch-message nil)
(scroll-bar-mode -1)
(tool-bar-mode -1)
(menu-bar-mode -1)
(global-font-lock-mode t)
(global-auto-revert-mode t)
(set-fringe-mode 8)
(display-battery-mode 1)
(size-indication-mode 1)
(save-place-mode 1)
(add-hook 'prog-mode-hook #'display-line-numbers-mode)
(setq visible-bell t)
;;(global-visual-line-mode t)
(defvar display-time-24hr-format t)
(display-time-mode 1)
(advice-add #'x-apply-session-resources :override #'ignore)
(unless (daemonp)
  (advice-add #'display-startup-echo-area-message :override #'ignore))
(setq frame-inhibit-implied-resize t)
(when (file-readable-p "~/.emacs.d/config.org")
  (org-babel-load-file (expand-file-name "~/.emacs.d/config.org")))
(provide 'early-init)
